name: publish-to-github-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js 🏗️
        run: |
          if [ -f next.config.js ]; then
            echo "⚠️ Found next.config.js - Deleting it..."
            rm next.config.js
          fi
          
          npx next build
        
      - name: Verify Output Directory
        run: |
          echo "🔍 Checking for 'out' folder..."
          if [ -d "out" ]; then
            echo "✅ Found 'out' folder! Contents:"
            ls -al out/
          else
            echo "❌ Error: 'out' folder not found!"
            exit 1
          fi

        working-directory: .

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4