name: publish-to-github-pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
        uses: ./.github/workflows/setup-node

      - name: Setup Pages ⚙️
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Build with Next.js 🏗️
        run: |
          if [ -f next.config.js ]; then
            echo "⚠️ Found next.config.js - Deleting it..."
            rm next.config.js
          fi

          # Build with production environment
          NODE_ENV=production npx next build

          # Verify public files were copied
          echo "✅ Public folder contents:"
          ls -al public/
          echo "✅ Out folder contents:"
          ls -R out | grep -E '.jpg|.png|.svg'  # 👈 Check for images

        working-directory: .

      - name: Upload artifact 📡
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out
        
      - name: Verify Built Images
        run: |
          echo "📷 Checking images in out folder:"
          find out -name "*.jpg" -o -name "*.png" -o -name "*.webp"
          echo "🌐 Checking image paths in HTML:"
          grep -Eroh 'src="[^"]*\.(jpg|png|webp)"' out/ || true

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Publish to GitHub Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4